# 1. 넘파이(numpy)

In [1]:
import numpy as np

In [2]:
# 설치가 안되어 있다면 다음과 같은 명령어로 설치하면 된다.
# pip install numpy

In [3]:
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)

[1 2 3 4 5]


In [4]:
[1, 2, 3, 4, 5] * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
arr_1 * 2

array([ 2,  4,  6,  8, 10])

In [6]:
arr_2 = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr_3 = np.array(
    [[[1, 2, 3], [4, 5, 6]],
     [[7, 8, 9], [10, 11, 12]],
     [[13, 14, 15], [16, 17, 18]]]
)
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [8]:
print(arr_1.dtype)

int64


In [9]:
print(np.array([1, 2, 3]).dtype)

int64


In [10]:
print(np.array([1, 2, 3], dtype='int8').dtype)

int8


In [11]:
print(np.array([1, 2, 3], dtype='i1').dtype)

int8


In [12]:
# 넘파이 배열을 사용하면 좋은 장점
# 1. 메모리 사용 효율이 좋고, 계산 속도가 빠름
# 2. 선형 대수 연산 지원
# 3. 벡터화 연산 지원

In [13]:
ndarray_1 = np.array([1, 2, 3])
ndarray_2 = np.array([4, 5, 6])
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]

In [14]:
print(ndarray_1 + ndarray_2)
print(list_1 + list_2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [15]:
print(ndarray_1 * 2)
print(list_1 * 2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [16]:
a = np.array([2, 3, 4])
print(a)
print(a.dtype)
b = np.array([2.1, 3.2, 4.3])
print(b)
print(b.dtype)

[2 3 4]
int64
[2.1 3.2 4.3]
float64


In [17]:
c = np.array(('i', 'j', 'k'))
print(c)
print(c.dtype)

['i' 'j' 'k']
<U1


In [18]:
d = np.array((True, True, False))
print(d)
print(d.dtype)

[ True  True False]
bool


In [19]:
e = np.array(['ab', 'cd', 'e'], dtype="<U2")
print(e)
print(e.dtype)

['ab' 'cd' 'e']
<U2


In [20]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
print(a.shape)
print(a.ndim) # 2차원
print(a.dtype) # 자료형
print(a.itemsize)

(3, 4)
2
int64
8


In [22]:
import numpy as np

# 1. 샘플 데이터 생성 (2학급, 3학생, 3과목)
# 점수는 50점에서 100점 사이의 랜덤한 정수로 생성합니다.
np.random.seed(42)  # 결과 재현을 위한 시드 설정
scores = np.random.randint(50, 101, size=(2, 3, 3))

print("전체 성적 데이터 (3차원 배열):")
print(scores)
print("-" * 30)

# 2. 특정 데이터 접근 예시
class1_student2_english = scores[0, 1, 1]  # 1반(0), 2번째 학생(1), 영어(1)
print(f"1반 2번 학생의 영어 점수: {class1_student2_english}")

# 3. 데이터 분석 활용
# 각 학급별 전 과목 평균
class_avg = scores.mean(axis=(1, 2))
print(f"1반 평균: {class_avg[0]:.2f}, 2반 평균: {class_avg[1]:.2f}")

# 각 과목별 전체 평균 (국, 영, 수)
subject_avg = scores.mean(axis=(0, 1))
print(f"국어 평균: {subject_avg[0]:.2f}, 영어 평균: {subject_avg[1]:.2f}, 수학 평균: {subject_avg[2]:.2f}")

전체 성적 데이터 (3차원 배열):
[[[88 78 64]
  [92 57 70]
  [88 68 72]]

 [[60 60 73]
  [85 89 73]
  [52 71 51]]]
------------------------------
1반 2번 학생의 영어 점수: 57
1반 평균: 75.22, 2반 평균: 68.22
국어 평균: 77.50, 영어 평균: 70.50, 수학 평균: 67.17


In [23]:
print(np.zeros((3, 4)))
print(np.zeros((3, 4), dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
print(np.ones((2, 3, 4), dtype=int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [25]:
print(np.empty((2, 3)))

[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


In [26]:
np.arange(10, 30, 5, int)

array([10, 15, 20, 25])

In [27]:
np.arange(start= 10, stop = 30, step = 5, dtype = int)

array([10, 15, 20, 25])

In [28]:
print(np.arange(10, 30, 5))
print(np.arange(start = 0, stop = 2, step = 0.3))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [29]:
print(np.linspace(start = 1, stop = 10, num = 10, endpoint=False, dtype = np.float16))

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [30]:
a = np.array([10, 20, 30, 40])
b = np.arange(start = 1, stop = 5)
print(a)
print(b)

[10 20 30 40]
[1 2 3 4]


In [31]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [32]:
print(a @ b)

300


In [33]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)
print(A @ B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [34]:
A = np.array([1, 2, 3, 4])
B = np.array([1, 1, 3, 3])
print(A > B)
print(A == B)

[False  True False  True]
[ True False  True False]


In [35]:
A = np.array([4, 16, 25])
print(np.sqrt(A))

[2. 4. 5.]


In [36]:
a = np.arange(8).reshape(2, 4) ** 2
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.cumsum())
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


In [37]:
a = np.arange(8).reshape(2, 4) ** 2
print(a.mean(axis = 0))
print(a.mean(axis = 1))

[ 8. 13. 20. 29.]
[ 3.5 31.5]


In [38]:
a

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [39]:
a.shape

(2, 4)

In [40]:
b = np.arange(30).reshape(2, 3, 5)

In [41]:
print(b.shape)

(2, 3, 5)


In [42]:
print(b.sum(axis = 0).shape)

(3, 5)


In [43]:
print(b.mean(axis = 1).shape)

(2, 5)


In [44]:
print(b.mean(axis = 2).shape)

(2, 3)


In [45]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [46]:
print(a[0])
print(a[3])

0
3


In [47]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

print(b[1, 0])
print(b[1, 2])

[[0 1 2]
 [3 4 5]]
3
5


In [48]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [49]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
b = a > 4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [51]:
print(a[b])
print(a[b].shape)

[ 5  6  7  8  9 10 11]
(7,)


In [52]:
a[b] = 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [53]:
A = np.arange(16).reshape(4, 4)
B = A < 5
A[B] = 0

In [54]:
print(A)

[[ 0  0  0  0]
 [ 0  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [55]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
i = np.array([1, 1, 3, 4])
print(a[i])
j = np.array([[3, 4], [5, 6]])

print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [56]:
b = np.array(['a', 'b', 'c', 'd'])
k = np.array([3, 2, 1, 0])

b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [57]:
a = np.arange(12).reshape(3, 4)
print(a)
print(a.shape)
print(a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [58]:
b = a.reshape(2, 6)
print(b)
print(b.shape)

print(a)
print(a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [59]:
c = a.reshape(-1, 3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [60]:
A = np.arange(30).reshape(2, 3, 5)
C = A.reshape(2, -1, 3)

In [61]:
C

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [62]:
a = np.arange(12)
a.resize(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
print(a.shape)

(4, 3)


In [64]:
print(a.resize(4, 3))

None


In [65]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
a = np.arange(12).reshape(3, 4)
print(a.ravel())
print(a.reshape(-1))
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [67]:
A = np.arange(12).reshape(2, 6)
print(A)
print(A.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [68]:
print(A.T.shape)

(6, 2)


In [69]:
A = A.T
print(A)
print(A.shape)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [70]:
a = np.arange(1, 17).reshape(4, 4)
np.linalg.det(a)

np.float64(0.0)

In [71]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [72]:
A = np.array([[1, -2, 3],
               [7, 5, 0],
               [-2, -1,2]])
np.linalg.inv(A)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [73]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array([5, 6, 7, 8]).reshape(2, 2)

print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [74]:
a = np.arange(12).reshape(2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [75]:
print(np.vsplit(a, 2))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]


In [76]:

print(np.hsplit(a, 3))

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [77]:
# 연습문제
# 1번
customer = np.array([[150, 25, 0], [200, 30, 0], [50, 10, 1], [300, 45, 0]])

In [78]:
print(customer)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]]


In [79]:
combined_data = np.vstack((customer, np.array([[120, 20, 0], [180, 35, 1], [75, 5, 0], [160, 25, 0]])))
print(combined_data)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]
 [120  20   0]
 [180  35   1]
 [ 75   5   0]
 [160  25   0]]


In [80]:
total_comment_length, total_likes, _ = combined_data.sum(axis=0)

In [81]:
total_comment_length, total_likes

(np.int64(1235), np.int64(195))

In [82]:
average_comment_length, average_likes, _ = combined_data.mean(axis=0)
average_comment_length, average_likes

(np.float64(154.375), np.float64(24.375))

In [83]:
print(f'댓글 길이 총합: {total_comment_length}')
print(f'좋아요 수 총합: {total_likes}')
print(f'댓글 길이 평균: {average_comment_length}')
print(f'좋아요 수 평균: {average_likes}')

댓글 길이 총합: 1235
좋아요 수 총합: 195
댓글 길이 평균: 154.375
좋아요 수 평균: 24.375


In [84]:
np.vsplit(combined_data, 4)

[array([[150,  25,   0],
        [200,  30,   0]]),
 array([[ 50,  10,   1],
        [300,  45,   0]]),
 array([[120,  20,   0],
        [180,  35,   1]]),
 array([[ 75,   5,   0],
        [160,  25,   0]])]

In [85]:
selected_customers = combined_data[[0, 2, 4]]
print(selected_customers)

[[150  25   0]
 [ 50  10   1]
 [120  20   0]]


In [86]:
combined_data.T

array([[150, 200,  50, 300, 120, 180,  75, 160],
       [ 25,  30,  10,  45,  20,  35,   5,  25],
       [  0,   0,   1,   0,   0,   1,   0,   0]])

In [87]:
new_customers = np.zeros((2, 3), dtype=np.int64)
print(new_customers)

[[0 0 0]
 [0 0 0]]


In [88]:
combined_data[:, 1] += 10

In [89]:
print(combined_data)

[[150  35   0]
 [200  40   0]
 [ 50  20   1]
 [300  55   0]
 [120  30   0]
 [180  45   1]
 [ 75  15   0]
 [160  35   0]]


In [90]:
a = combined_data[:, 0] >= 100
b = combined_data[:, 1] >= 20
c = combined_data[:, 2] == 0
print(a)
print(b)
print(c)

[ True  True False  True  True  True False  True]
[ True  True  True  True  True  True False  True]
[ True  True False  True  True False  True  True]


In [91]:
np.all((a, b, c), axis=0)

array([ True,  True, False,  True,  True, False, False,  True])

In [92]:
selected_customers = combined_data[np.all((a, b, c), axis=0)]
print(selected_customers)

[[150  35   0]
 [200  40   0]
 [300  55   0]
 [120  30   0]
 [160  35   0]]


In [94]:
# 10번 문제
print(f'상품을 받을 고객 수: {len(selected_customers)}')

상품을 받을 고객 수: 5
