In [1]:
import pandas as pd

wine = pd.read_csv('wine.csv')

wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [2]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   alcohol  6497 non-null   float64
 1   sugar    6497 non-null   float64
 2   pH       6497 non-null   float64
 3   class    6497 non-null   float64
dtypes: float64(4)
memory usage: 203.2 KB


In [3]:
wine.describe()

alcohol        sugar           pH        class
count  6497.000000  6497.000000  6497.000000  6497.000000
mean     10.491801     5.443235     3.218501     0.753886
std       1.192712     4.757804     0.160787     0.430779
min       8.000000     0.600000     2.720000     0.000000
25%       9.500000     1.800000     3.110000     1.000000
50%      10.300000     3.000000     3.210000     1.000000
75%      11.300000     8.100000     3.320000     1.000000
max      14.900000    65.800000     4.010000     1.000000

In [4]:
inputs = wine[['alcohol', 'sugar', 'pH']].to_numpy()
targets = wine['class'].to_numpy()

In [5]:
print(inputs[:5])

[[9.4  1.9  3.51]
 [9.8  2.6  3.2 ]
 [9.8  2.3  3.26]
 [9.8  1.9  3.16]
 [9.4  1.9  3.51]]


In [6]:
print(targets[:5])

[0. 0. 0. 0. 0.]


In [7]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(inputs, targets, test_size=0.2, random_state=42)
print(train_input[:5])
print(train_target[:5])

[[10.5   7.7   3.19]
 [12.4   2.1   3.26]
 [11.8   2.1   3.41]
 [11.7   1.2   3.37]
 [ 9.3  15.4   3.11]]
[1. 0. 0. 1. 1.]


In [8]:
print(train_input.shape, train_target.shape)

(5197, 3) (5197,)


In [9]:
import pandas as pd

wine = pd.read_csv('wine.csv')

wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [12]:
from sklearn.model_selection import train_test_split

inputs = wine[['alcohol', 'sugar', 'pH']].to_numpy()
targets = wine['class'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(
    inputs, targets, test_size=0.2, random_state=42
)

In [13]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

In [17]:
from sklearn.model_selection import StratifiedKFold, KFold, cross_validate, cross_val_score
# cross_val_score는 교차 검증 후 test_score만 반환

stratified_kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42) # StratifiedKFold는 분류 문제

scores = cross_validate(dt, train_input, train_target, cv=stratified_kfold)

print(scores)

{'fit_time': array([0.0061357 , 0.00553036, 0.00546432, 0.00476789, 0.0049808 ,
       0.00468326, 0.00612211, 0.00438142, 0.00433135, 0.00410819]), 'score_time': array([0.00039029, 0.        , 0.        , 0.00103402, 0.00099611,
       0.00108409, 0.00107813, 0.0010941 , 0.00112057, 0.00108242]), 'test_score': array([0.83461538, 0.88076923, 0.84615385, 0.85961538, 0.84423077,
       0.87115385, 0.86538462, 0.85163776, 0.85549133, 0.87861272])}


In [18]:
print(scores['test_score'])

[0.83461538 0.88076923 0.84615385 0.85961538 0.84423077 0.87115385
 0.86538462 0.85163776 0.85549133 0.87861272]


In [20]:
import numpy as np

print(np.mean(scores['test_score']))

0.8587664888098413


In [21]:
from sklearn.model_selection import GridSearchCV

params = {'min_impurity_decrease': np.arange(0.0001, 0.0006, 0.0001)}

gs = GridSearchCV(dt, params, n_jobs=-1, cv=stratified_kfold)

In [22]:
gs.fit(train_input, train_target)

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005])})

In [23]:
print(gs.score(train_input, train_target))

0.9617086780835097


In [24]:
print(gs.best_params_)

{'min_impurity_decrease': np.float64(0.0001)}


In [27]:
print(gs.cv_results_['mean_test_score'])

[0.86819327 0.86338039 0.86607529 0.86068994 0.85972617]


In [28]:
print(np.argmax(gs.cv_results_['mean_test_score']))

0


In [29]:
print(gs.cv_results_["params"][np.argmax(gs.cv_results_['mean_test_score'])])

{'min_impurity_decrease': np.float64(0.0001)}


In [30]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
          'max_depth': range(5, 20, 1),
          'min_samples_split': range(2, 100, 10)
          }

In [31]:
gs = GridSearchCV(dt, params, n_jobs=-1, cv=stratified_kfold)
gs.fit(train_input, train_target)

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [32]:
print(gs.best_params_)

{'max_depth': 18, 'min_impurity_decrease': np.float64(0.0001), 'min_samples_split': 2}


In [33]:
print(np.max(gs.cv_results_['mean_test_score']))

0.871846746702238


In [ ]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV()